[package]
name = "partition_search_cpu"
version = "0.1.0"
edition = "2021"

[dependencies]
cuda_std = "0.2.2"
cust = "0.3.2"
partition_search_gpu = { path = "../partition_search_gpu" }
itertools = "0.10.3"

[build-dependencies]
cuda_builder = "0.3.0"